import store, {
  AppDispatch, AppThunk, rootReducer, RootState,
} from './store';
import {
  clearFinishedState,
  nextFibonacchiStep,
  nextSortingStep,
  nextStackStep,
  nextStringReverseStep,
  resetFibonacchi,
  resetSorting,
  resetStack,
  resetString,
  startFibonachhi,
  startSorting,
  startStack,
  startStringReverse,
  stopFibonacchi,
  stopSorting,
  stopStack,
  stopStringReverse,
  startQueue,
  stopQueue,
  nextQueueStep,
  resetQueue,
} from './view-slice';
import {
  clearFibonacchiLimit,
  clearIndex,
  clearItem,
  clearRandomArray,
  clearSortingDirections,
  clearSortingType,
  clearString,
  setFibonacchiLimit,
  setIndex,
  setItem,
  setRandomArray,
  setSortingDirection,
  setSortingType,
  setString,
} from './forms-slice';

export {
  store,
  rootReducer,
  startStringReverse,
  stopStringReverse,
  nextStringReverseStep,
  resetString,
  clearFinishedState,
  startFibonachhi,
  stopFibonacchi,
  nextFibonacchiStep,
  resetFibonacchi,
  startSorting,
  stopSorting,
  nextSortingStep,
  resetSorting,
  setString,
  clearString,
  setFibonacchiLimit,
  clearFibonacchiLimit,
  setRandomArray,
  clearRandomArray,
  setSortingType,
  setSortingDirection,
  clearSortingType,
  clearSortingDirections,
  startStack,
  stopStack,
  nextStackStep,
  resetStack,
  setItem,
  clearItem,
  setIndex,
  clearIndex,
  startQueue,
  stopQueue,
  nextQueueStep,
  resetQueue,
};

export type {
  RootState,
  AppDispatch,
  AppThunk,
};
